services:
  spring-app:
    image: eclipse-temurin:17-jdk
    container_name: spring-backbone
    working_dir: /app
    volumes:
      - /srv/backbone/target:/app
    command: ["java", "-jar", "/app/backbone.jar"]
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=${MONGODB_URI}
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
    ports:
      - '8000:8000'
    networks:
      - dbnet
    profiles:
      - prod

networks:
  dbnet:
    external: true




