services:
  spring-app:
    image: eclipse-temurin:17-jdk
    container_name: spring-backbone
    working_dir: /app
    volumes:
      - ./target:/app
    command: java -jar backbone.jar
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    profiles:
      - prod

